### ISSUE TITLE
rte block location in the canvas

### ISSUE THREAD

**Issue by mostafaecm** [Ju99ernaut/grapesjs-rte-extensions#13]
Hi .
After activating rte in grapesjs, when the text is in a small block, the rte block is placed on the text and the text cannot be edited. Also, when the text is in the corners of the canvas, the rte block pops out of the canvas and some options are not displayed (hide out of the canvas). Is there a solution to the rte block location problem?

**Comment by JakeMass** [comment]
Hi, I've also observed the same problem, although this mostly occurs when trying to edit a textblock the first time. After deselecting a block and selecting it again the rte-toolbar positiones itself the right way. So there seems to be a problem in the initial positioning of the toolbar.

**Comment by sneddobuilds** [comment]
Hi - I see this is closed but wanted to post for anyone who happens along here in the future. 

You can adjust the position of the toolbar with the 'rteToolbarPosUpdate' event. 

` editor.on('rteToolbarPosUpdate', (pos) => {
                let toolbarDiv = editor.RichTextEditor.getToolbarEl()
                let toolbarHeight = toolbarDiv.scrollHeight
                let toolbarWidth = toolbarDiv.scrollWidth
                let rect = editor.Canvas.getRect()
                if (pos.top <= 0 && pos.top > -8) {
                    
                    pos.top = (rect.height - toolbarHeight) + (pos.top - pos.canvasOffsetTop)
                }
                
                //check to see if the tool bar will go out of the screen and offset the left pos if it will.
                let overhangLeft = rect.width - (toolbarWidth + pos.canvasOffsetLeft);
                if(overhangLeft < 0)
                {
                    pos.left = (overhangLeft -5)
                }
                
            });`
