### ISSUE TITLE
How to enable "wrap for style"?

### ISSUE THREAD

**Issue by sneddobuilds** [Ju99ernaut/grapesjs-rte-extensions#22]
I see in the demo there is this: 
![image](https://user-images.githubusercontent.com/76793034/155599579-33f3e4ee-210b-4b45-9d46-a6641f4be21f.png)

But I can't work out how to turn it on via the options. 

Has it been removed in more recent versions? If so can you point me at the code it exists in so I can create a version with it in?

**Comment by Ju99ernaut** [comment]
It's part of the core rte and only available in the latest version of `grapesjs`, so update to latest version.
