### ISSUE TITLE
data-gjs-type="text" is changed to data-gjs-type="default" after saving

### ISSUE THREAD

**Issue by ankursinghagra** [Ju99ernaut/grapesjs-rte-extensions#24]
Hi, 
I am having an issue upon saving and retrieving data later. 
This is how the code looks like when i drag a text element:
`<div data-gjs-highlightable="true" id="iitt4" data-gjs-type="text" draggable="true" jsonid="5" class="gjs-selected" contenteditable="false">Insert your text here</div>`

And this is when i have updated it with RTE extension 
`<div data-gjs-highlightable="true" id="iitt4" data-gjs-type="text" draggable="false" jsonid="5" class="gjs-selected" contenteditable="true"><b>Insert <i>your text</i> here</b></div>`

And after saving and retrieving after refresh 
`<div data-gjs-highlightable="true" id="idtqi" data-gjs-type="default" draggable="true" class="gjs-selected"><b data-gjs-highlightable="true" id="iwov5" data-gjs-type="text" draggable="true">Insert <i id="iv84i" data-gjs-type="text" draggable="true">your </i>text <i id="ii0al" data-gjs-type="text" draggable="true" class="">here</b></div>
`

Notice how `data-gjs-type="text"` is changed to `data-gjs-type="default"`. This causes plugin to get unstable

**Comment by Ju99ernaut** [comment]
Looks like an issue with your storage. You should always rely on the json provided by the editor for storage and loading.
