### ISSUE TITLE
Clear formatting does not appear to remove the background color

### ISSUE THREAD

**Issue by bmarsh9** [Ju99ernaut/grapesjs-rte-extensions#26]
Hey there,

Going off the demo you have, I'm unable to remove the background color of text using the ClearFormatting button on the toolbar. It works fine for removing the text color, however it doesn't remove the background.

**Comment by bmarsh9** [comment]
Also trying to update the background color does not appear to work

**Comment by Ju99ernaut** [comment]
Yeah the plugin relies on the `document.execcommand` which doesn't work consistently across browsers so I don't think there's much I can do about this one.

**Comment by bmarsh9** [comment]
Got it - thanks
