### ISSUE TITLE
Bullet and Number no longer auto-added on new line as of grapesjs 0.18.3

### ISSUE THREAD

**Issue by barryross** [Ju99ernaut/grapesjs-rte-extensions#30]
As of grapesjs version 0.18.3, when working with a list (ol or ul) in the RTE, pressing return no longer adds a new bullet or number.  

Anybody have any workarounds? 

To reproduce:

1. Select piece of text on Canvas
2. Click ul in RTE
3. Add bullet point
4. Press return

**Comment by Ju99ernaut** [comment]
This uses a browser API so it's hard to figure out why some issues arise.

**Comment by barryross** [comment]
@skru great, thank you!

**Comment by skru** [comment]
This isn't anything to do with execCommand as I thought initially (only learnt about it yesterday and when I saw the deprecation warnings I panicked!)

I think it is down to the changes introduced in[ this commit](https://github.com/artf/grapesjs/commit/40fa88f278e6f70c825e1f3b163b66a5d9d3301f) but ran out of time today. 

Roughly around stopping clicks propagating. Any ideas @Ju99ernaut ?

**Comment by skru** [comment]
See: [https://github.com/artf/grapesjs/issues/4449](https://github.com/artf/grapesjs/issues/4449)

**Comment by Ju99ernaut** [comment]
I believe this has been fixed in core
